version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # network:
    #   - something
  backend:
    build: ./services/server
    ports:
      - "5000:5000"
    # network:
    #   - something
# networks:
#   something:
