# Development environment
version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "8123:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
